# Introduction to Tensorflow

- A Tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, Tensorflow represents tensors as n-dimensional arrays of base datatypes.

- Vector is kind of a data point.   
    - 2d datapoint have a x coordinate and y coordinate.
    - 3d datapoints have 3 coordinates and so on.
    - But a vector have n-dimensions according to the datapoints' dimension.

- Datatype is what type of information saved in a tensor (integer, float).
- Scaler means just one value.

## Creating Tensors

In [3]:
import tensorflow as tf

string = tf.Variable("this is a string", tf.string)
number = tf.Variable(10, tf.int16)
floating = tf.Variable(3.142, tf.float64)

## Rank/ Degree of Tensors

Another word for rank is degree, these terms simply mean the number of **dimensions** invloved in the tensor. What we created above is a tensor of **rank 0**, also known as a **Scaler**.

In [13]:
# ranks with highere dimensions

rank1_tensor = tf.Variable(["one","two"], tf.string)
rank2_tensor = tf.Variable([["one","two","1"],["three","four", "2"]], tf.string)
rank3_tensor = tf.Variable([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]], tf.int16)

In [15]:
# determine the rank of a tensor
print(tf.rank(string))
print(tf.rank(rank1_tensor))
print(tf.rank(rank2_tensor))
print(tf.rank(rank3_tensor))

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


## Shape of Tensors


The Shape of a tensor means the amount of elements that exist in each dimension.

In [16]:
# shape of a tensor

print(string.shape)
print(rank1_tensor.shape)
print(rank2_tensor.shape)   
print(rank3_tensor.shape)

()
(2,)
(2, 3)
(2, 2, 3)


## Changing Shape

The number of elements of a tensor is the product of the sizes of all its shapes.

In [17]:
tensor1 = tf.ones([1,2,3])  # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1])  # reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
                                        # this will reshape the tensor to [3,3]

In [19]:
print(tensor1, "\n")
print(tensor2, "\n")
print(tensor3, "\n")

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32) 

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32) 

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32) 



# Types of Tensors

- Constant
- Variable
- Placeholder
- SparseTensor

- Except Variable, other types are **immutable**.


## Evaluating Tensors

- By evaluating a tensor, we get a value.
- Since tensors represent a partially complete computation we will sometimes need to run whats called a session to evaluate the tensor.

In [29]:
t = tf.zeros([2,2,5])

t = tf.reshape(t, [-1, 5])
print(t)

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(4, 5), dtype=float32)
